name: Build & deploy

on:
  schedule:
  - cron: '0 10 * * SUN'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, fetch data and build
      run: |
        npm install
        npm run fetch:data "${{ secrets.FETCH_DATA_TOKEN }}"
        npm run build
      env:
        CI: true
    - name: deploy
      uses: crazy-max/ghaction-github-pages@master
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PAT: ${{ secrets.FETCH_DATA_TOKEN }}
